### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by jarun** [jarun/googler#112]
**Issue 1: googler exits if p is pressed at first page**
Expected: It shouldn't exit and we shouldn't point it as an `ERROR`. Just `Already at the first page.` should do.

And why are we raising an exception for this? Just printing the message and maintaining start at 0 should do.

```
$ googler -d bohoomil infinality deb package 16.04 ubuntu -t m3
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=bohoomil+infinality+deb+package+16.04+ubuntu&start=0&tbs=qdr:m3
[DEBUG] Redirecting to URL https://www.google.co.in/search?ie=UTF-8&num=10&oe=UTF-8&q=bohoomil+infinality+deb+package+16.04+ubuntu&start=0&tbs=qdr:m3&gws_rd=cr&ei=htlYV7T0PIP_vgTampT4AQ
[DEBUG] Connecting to new host www.google.co.in
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=bohoomil+infinality+deb+package+16.04+ubuntu&start=0&tbs=qdr:m3&gws_rd=cr&ei=htlYV7T0PIP_vgTampT4AQ
[DEBUG] Response body written to '/tmp/googler-response-tpi1kded'.

1 Ubuntu 16.04 support · Issue #25 · achaphiv/ppa-fonts · GitHub
https://github.com/achaphiv/ppa-fonts/issues/25
Apr 21, 2016 - Please build both freetype and fontconfig-infinality for ubuntu 16.04. thanks. ... It looks like
bohoomil's patch for freetype 2.6.1 is no longer applying. Might be simpler ... Thank you for your work despite
hating debian packaging :). @greatquux.

2 Install fonts and improve font rendering quality in Arch Linux
http://www.ostechnix.com/install-fonts-improve-font-rendering-quality-arch-linux/
May 6, 2016 - infinality. For the past two years, I have been using Ubuntu as my primary OS, but now it's Arch
Linux with Deepin Desktop ... [infinality-bundle] Server = http://bohoomil.com/repo/$arch ... The package name
will be given in the left side for each language set. ... Install Nginx, MariaDB, PHP (LEMP Stack) in Ubuntu
16.04 LTS.

3 Shell Github Star Ranking at 2016/05/06 - Main
https://38elements.github.io/2016/05/06/shell-repository-github-star-ranking.html
May 6, 2016 - Nyr/openvpn-install 1677 OpenVPN road warrior installer for Debian, Ubuntu and ..... for the
terminal. bohoomil/fontconfig-ultimate 330 freetype2-infinality run-time ... IPsec/L2TP VPN server on Ubuntu
16.04/14.04/12.04, Debian 8 and CentOS ...

4 Después de instalar openSUSE Leap 42.1 KDE | La sombra del ...
http://lasombradelhelicoptero.com/despues-de-instalar-opensuse-leap-42-1-kde/
May 11, 2016 - ... que asegura incorporar los parches del famoso usuario Bohoomil de Arch Linux. ... Infinality
openSUSE ... Si no están instaladas, como las fuentes de Ubuntu, por ejemplo, las encontraréis en la web de
software de openSUSE. ..... Synchronizing package databases… .... Ubuntu 16.04 Xenial Xerus: un futuro
prometedor.

googler (? for help) p
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 1859, in <module>
    main()
  File "/usr/local/bin/googler", line 1848, in main
    repl.cmdloop()
  File "/usr/local/bin/googler", line 1643, in cmdloop
    self.do_previous('')
  File "/usr/local/bin/googler", line 1378, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1392, in enforced_method
    method(self)
  File "/usr/local/bin/googler", line 1608, in do_previous
    self._google_url.prev_page()
  File "/usr/local/bin/googler", line 347, in prev_page
    raise ValueError('Already at the first page.')
ValueError: Already at the first page.
```

**Issue 2: Redundant newline and WARNING message when no more results**

Expected: No warning in an informative message please. Just `No results.` should do. And we need to remove the extra newline above the message.

```
$ googler -d bohoomil infinality deb package 16.04 ubuntu -t m3
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=bohoomil+infinality+deb+package+16.04+ubuntu&start=0&tbs=qdr:m3
[DEBUG] Redirecting to URL https://www.google.co.in/search?ie=UTF-8&num=10&oe=UTF-8&q=bohoomil+infinality+deb+package+16.04+ubuntu&start=0&tbs=qdr:m3&gws_rd=cr&ei=jdpYV6yYO8nqvAT4y4-YDg
[DEBUG] Connecting to new host www.google.co.in
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=bohoomil+infinality+deb+package+16.04+ubuntu&start=0&tbs=qdr:m3&gws_rd=cr&ei=jdpYV6yYO8nqvAT4y4-YDg
[DEBUG] Response body written to '/tmp/googler-response-l5dsr7is'.

1 Ubuntu 16.04 support · Issue #25 · achaphiv/ppa-fonts · GitHub
https://github.com/achaphiv/ppa-fonts/issues/25
Apr 21, 2016 - Please build both freetype and fontconfig-infinality for ubuntu 16.04. thanks. ... It looks like
bohoomil's patch for freetype 2.6.1 is no longer applying. Might be simpler ... Thank you for your work despite
hating debian packaging :). @greatquux.

2 Install fonts and improve font rendering quality in Arch Linux
http://www.ostechnix.com/install-fonts-improve-font-rendering-quality-arch-linux/
May 6, 2016 - infinality. For the past two years, I have been using Ubuntu as my primary OS, but now it's Arch
Linux with Deepin Desktop ... [infinality-bundle] Server = http://bohoomil.com/repo/$arch ... The package name
will be given in the left side for each language set. ... Install Nginx, MariaDB, PHP (LEMP Stack) in Ubuntu
16.04 LTS.

3 Shell Github Star Ranking at 2016/05/06 - Main
https://38elements.github.io/2016/05/06/shell-repository-github-star-ranking.html
May 6, 2016 - Nyr/openvpn-install 1677 OpenVPN road warrior installer for Debian, Ubuntu and ..... for the
terminal. bohoomil/fontconfig-ultimate 330 freetype2-infinality run-time ... IPsec/L2TP VPN server on Ubuntu
16.04/14.04/12.04, Debian 8 and CentOS ...

4 Después de instalar openSUSE Leap 42.1 KDE | La sombra del ...
http://lasombradelhelicoptero.com/despues-de-instalar-opensuse-leap-42-1-kde/
May 11, 2016 - ... que asegura incorporar los parches del famoso usuario Bohoomil de Arch Linux. ... Infinality
openSUSE ... Si no están instaladas, como las fuentes de Ubuntu, por ejemplo, las encontraréis en la web de
software de openSUSE. ..... Synchronizing package databases… .... Ubuntu 16.04 Xenial Xerus: un futuro
prometedor.

googler (? for help) n
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=bohoomil+infinality+deb+package+16.04+ubuntu&start=10&tbs=qdr:m3
[DEBUG] Response body written to '/tmp/googler-response-7j__n2jy'.

[WARNING] No results.
googler (? for help)
```

**Comment by jarun** [comment]
For issue 1:

Retaining and catching ValueError, then printing (not logging) the message.

For issue 2:

The newline has appeared because we want to show a newline above every result. In this case erasing the last newline.
