### ISSUE TITLE
[ERROR] Got HTTP 302: Found

### ISSUE THREAD

**Issue by ljhui** [jarun/googler#145]
googler is a desired command line tool ,but it doesn't work for me,when I use it on Fedora24,the gnome terminal always return `[ERROR] Got HTTP 302: Found`,I think maybe because I use lantern or hosts to 
breakthrough GFW, the origin google site redirects to google in HongKong or Janpanse,but I can use google in browser .

```
ljhui@thinkpad  ~  googler hello
[ERROR] Got HTTP 302: Found
 ✘ ljhui@thinkpad  ~  googler -d
[DEBUG] Version 2.8
[DEBUG] Connecting to new host www.google.com
Please initiate a query.
googler (? for help) hello
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=hello&start=0
[DEBUG] Cookie: NID=91=pV0JnSZUq0nSHIYK3xY2sHV6Wpo4xCeuZWLbfWQ9CGi6SDAQmfgPjApL19dmZujvlxGmJFg7-PR-4FoyHEyX6Zb_CmQ3WGwWTVLKNrRZC81WPkuwg34tbtkTE-fBAItU
[DEBUG] Redirecting to URL http://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/search%3Fie%3DUTF-8%26num%3D10%26oe%3DUTF-8%26q%3Dhello%26start%3D0%26gws_rd%3Dcr&ust=1479739824846540&usg=AFQjCNElLi_CKIxaPN3yhPRj8fcOCxrGaA
[DEBUG] Connecting to new host www.google.com.hk
[DEBUG] Fetching URL /url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/search%3Fie%3DUTF-8%26num%3D10%26oe%3DUTF-8%26q%3Dhello%26start%3D0%26gws_rd%3Dcr&ust=1479739824846540&usg=AFQjCNElLi_CKIxaPN3yhPRj8fcOCxrGaA
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2179, in <module>
    main()
  File "/usr/local/bin/googler", line 2168, in main
    repl.cmdloop()
  File "/usr/local/bin/googler", line 1809, in cmdloop
    self.do_google(cmd)
  File "/usr/local/bin/googler", line 1734, in do_google
    self.fetch_and_display()
  File "/usr/local/bin/googler", line 1519, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1679, in fetch_and_display
    self.fetch()
  File "/usr/local/bin/googler", line 1519, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1610, in fetch
    page = self._conn.fetch_page(self._google_url.relative())
  File "/usr/local/bin/googler", line 672, in fetch_page
    raise GoogleConnectionError('Got HTTP %d: %s' % (resp.status, resp.reason))
__main__.GoogleConnectionError: Got HTTP 302: Found
```

**Comment by zmwangx** [comment]
The problem is we only allow a one-time redirection, where you're being redirected multiple times. We've never seen this before. We could account for that, but I'd like to see the output of

```
$ curl -IL 'https://www.google.com/search?ie=UTF-8&num=10&oe=UTF-8&q=hello&start=0'
```

first.

**Comment by ljhui** [comment]
This is the output.
```
HTTP/2.0 302
location:http://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=http://www.google.com.hk/search%3Fie%3DUTF-8%26num%3D10%26oe%3DUTF-8%26q%3Dhello%26start%3D0%26gws_rd%3Dcr&ust=1479741695593074&usg=AFQjCNFmRK-sL5glg4DdaUqjmP0JLeeWrg
cache-control:private
content-type:text/html; charset=UTF-8
p3p:CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."
date:Mon, 21 Nov 2016 15:21:05 GMT
server:gws
content-length:457
x-xss-protection:1; mode=block
x-frame-options:SAMEORIGIN
set-cookie:NID=91=YYS9gxV-B7BNvTYLtC_MO4-Hn-EClk_-onFBUUW7LDved8-ibIsjQmgIZVzkRtytk8qkawT82uPnSm0avI5wo11fH_5PEzd7Wr5GHBdtoxOGzKIJIxVi5cF7SQdnyTHX; expires=Tue, 23-May-2017 15:21:05 GMT; path=/; domain=.google.com; HttpOnly
alt-svc:quic=":443"; ma=2592000; v="36,35,34"

curl: (56) Recv failure: Connection reset by peer
```

**Comment by zmwangx** [comment]
That doesn't help, you can't even finish the request with curl.

I don't know how Lantern works and can't seem to find an explanation (other than "better than a VPN" which is apparently marketing bullshit). My guess is it's a per-process proxy that covers your browsers but doesn't work with arbitrary processes like curl or googler's python.

**Comment by zmwangx** [comment]
Nevertheless, you could try this patch.

```diff
From 080bbf51114e0d6ea87f9887564edf343a49a8a2 Mon Sep 17 00:00:00 2001
From: Zhiming Wang <zmwangx@gmail.com>
Date: Mon, 21 Nov 2016 10:22:35 -0500
Subject: [PATCH] googler: allow multiple redirects

Fixes #145.
---
 googler | 21 +++++++++++++--------
 1 file changed, 13 insertions(+), 8 deletions(-)

diff --git a/googler b/googler
index 4f055d4..07c63b2 100755
--- a/googler
+++ b/googler
@@ -627,8 +627,8 @@ class GoogleConnection(object):
     def fetch_page(self, url):
         """Fetch a URL.
 
-        Allows one reconnection and one redirection before failing and
-        raising GoogleConnectionError.
+        Allows one reconnection and multiple redirections before failing
+        and raising GoogleConnectionError.
 
         Parameters
         ----------
@@ -661,12 +661,17 @@ class GoogleConnection(object):
                 raise GoogleConnectionError("Failed to get '%s'." % url)
 
         resp = self._resp
-        if resp.status in {301, 302, 303, 307, 308}:
-            redirection_url = resp.getheader('location', '')
-            if 'sorry/IndexRedirect?' in redirection_url:
-                raise GoogleConnectionError('Connection blocked due to unusual activity.')
-            self._redirect(redirection_url)
-            resp = self._resp
+        redirect_counter = 0
+        while resp.status != 200 and redirect_counter < 5:
+            if resp.status in {301, 302, 303, 307, 308}:
+                redirection_url = resp.getheader('location', '')
+                if 'sorry/IndexRedirect?' in redirection_url:
+                    raise GoogleConnectionError('Connection blocked due to unusual activity.')
+                self._redirect(redirection_url)
+                resp = self._resp
+                redirect_counter += 1
+            else:
+                break
 
         if resp.status != 200:
             raise GoogleConnectionError('Got HTTP %d: %s' % (resp.status, resp.reason))
-- 
2.10.2

```

Also available as a gist: https://gist.github.com/anonymous/48f5aef33bcef4d40efe5548f30b5f69.

**Comment by zmwangx** [comment]
As expected, Lantern configures the system proxy with a PAC file. Sorry, googler doesn't support that (neither does curl/wget/etc.). You might be able to find out which proxy nodes Lantern is connecting to (with tcpdump or Wireshark for instance) and manually set the proxy with our `--proxy` option.

**Comment by zmwangx** [comment]
Closed by accident... But I doubt we can do much about your PAC problem, since we need to be JavaScript-capable to be able to support PAC, which apparently won't happen.

Feel free to ask questions though, I'd be happy to provide pointers if I can.
