### ISSUE TITLE
got [ERROR] Failed to connect to www.google.com: EOF occurred in violation of protocol (_ssl.c:645).

### ISSUE THREAD

**Issue by 123yagel** [jarun/googler#151]
```
$ googler -d
[DEBUG] Version 2.8
[DEBUG] Connecting to new host www.google.com
Please initiate a query.
googler (? for help) google
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=google&start=0
[DEBUG] Cookie: NID=91=XX4DLRXxgTeBN1qr3ctP7u6QhwZ1yNuNNLjhMVoITsG_wkvI655sOxjuT6v83M-5FE2YT85xitEtRp-DicnlFOLOPCUMgLyGIpY2ccVM43nN94mkCZoD0bHFpgkFR1ir
[DEBUG] Redirecting to URL https://www.google.co.il/search?ie=UTF-8&num=10&oe=UTF-8&q=google&start=0&gws_rd=cr&ei=N_5HWKGSL8frUqGhoegM
[DEBUG] Connecting to new host www.google.co.il
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 614, in new_connection
    self._conn.connect(self._notweak)
  File "/usr/local/bin/googler", line 166, in connect
    ssl_version=ssl.PROTOCOL_TLSv1_2)
  File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2166, in <module>
    main()
  File "/usr/local/bin/googler", line 2155, in main
    repl.cmdloop()
  File "/usr/local/bin/googler", line 1809, in cmdloop
    self.do_google(cmd)
  File "/usr/local/bin/googler", line 1734, in do_google
    self.fetch_and_display()
  File "/usr/local/bin/googler", line 1519, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1679, in fetch_and_display
    self.fetch()
  File "/usr/local/bin/googler", line 1519, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1610, in fetch
    page = self._conn.fetch_page(self._google_url.relative())
  File "/usr/local/bin/googler", line 668, in fetch_page
    self._redirect(redirection_url)
  File "/usr/local/bin/googler", line 703, in _redirect
    self.new_connection(host)
  File "/usr/local/bin/googler", line 617, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.co.il: EOF occurred in violation of protocol (_ssl.c:645).

```

```
$ python3 --version
Python 3.5.2
```

```
$ uname -a
Linux <my computer name> 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ gnome-terminal --version
GNOME Terminal 3.18.3
```

```
$ bash --version
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by jarun** [comment]
Can you please run the test with the latest master branch?

**Comment by zmwangx** [comment]
You didn't say if this error is sporadic. If it is, shitty connection it is. You can also try to curl/wget `https://www.google.co.il/search?ie=UTF-8&num=10&oe=UTF-8&q=google&start=0&gws_rd=cr&ei=N_5HWKGSL8frUqGhoegM`. Again, shitty connection if curl/wget (sometimes) fails.

In addition, Ubuntu and OpenSSL versions may be helpful.

**Comment by 123yagel** [comment]
```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
The bug apears 'sometimes'. I don't think it is shitty connection because when the bug was, I could search in the browser or `ping google.com`, and `wget` return `403 Forbidden` as shown bellow.

this debug is differ from the first I gave. In the first it crashes after the redirecting and now it does before it:
```
$ googler google -d
[DEBUG] Version 2.8
[DEBUG] Connecting to new host www.google.com
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 614, in new_connection
    self._conn.connect(self._notweak)
  File "/usr/local/bin/googler", line 166, in connect
    ssl_version=ssl.PROTOCOL_TLSv1_2)
  File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2166, in <module>
    main()
  File "/usr/local/bin/googler", line 2140, in main
    repl = GooglerCmd(opts)
  File "/usr/local/bin/googler", line 1576, in __init__
    notweak=opts.notweak)
  File "/usr/local/bin/googler", line 565, in __init__
    self.new_connection(host, port=port, timeout=timeout)
  File "/usr/local/bin/googler", line 617, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.com: EOF occurred in violation of protocol (_ssl.c:645).
```

sometimes it works: (The result is in Hebrew but you can see the debug)
```
$ googler google -d
[DEBUG] Version 2.8
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=google&start=0
[DEBUG] Cookie: NID=91=JQpNPIv6X_BeyYWROPQ8Z7r2SHNlDl91gzQvUnH78F_sVPRXK8lnaedwHIhw1_ip2qgVjNrt7BvZzT2OwdwhnjbjVMDTO35uBjDxyjfUyNGXVYdaSxdEHt4IwSBgGRVT
[DEBUG] Redirecting to URL https://www.google.co.il/search?ie=UTF-8&num=10&oe=UTF-8&q=google&start=0&gws_rd=cr&ei=24dIWKW2CcKaU6mCEw
[DEBUG] Connecting to new host www.google.co.il
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=google&start=0&gws_rd=cr&ei=24dIWKW2CcKaU6mCEw
[DEBUG] Response body written to '/tmp/googler-response-nkhpa1_m'.

1 Google 
https://www.google.co.il/
הגרסה העברית של מנוע החיפוש הידוע: חיפוש דפים ותמונות ועותק של המדריך הפתוח.

    1a Google Translate
    https://translate.google.co.il/m/translate
    מידע על Google Translate · קהילה · קלאסי · פרטיות ותנאים · עזרה; שלח ...

    1b תרגם
    https://translate.google.co.il/
    Translateכבה תרגום מהיר ... לעסקים:כלי תרגוםמתרגם אתרמאתר השווקים ...

    1c תרגום
    https://translate.google.co.il/?hl=iw
    השירות של Google מתרגם באופן מיידי ובחינם מילים, ביטויים ודפי אינטרנט ...

    1d Google
    https://www.google.co.il/?gws_rd=ssl
    Google.co.il גם ב: العربية English · הגדרות הגדרות חיפוש חיפוש ...

2 Google 
https://www.google.com/?hl=he
... Gmail · Drive · יומן · עוד · תרגם · Google לנייד · Blogger · תצלומים · Docs · ועוד יותר » ... פרסום ב-Googleהכל על GoogleGoogle.com in English. ©
2016 - פרטיות - תנאים.

3 Google - YouTube 
https://www.youtube.com/user/Google
Experience the world of Google on our official YouTube channel. Watch videos about our products, technology, company happenings and more. Subscribe
to ...

4 Google | Facebook 
https://www.facebook.com/Google/
Google, Mountain View, CA. 21243649 likes · 101493 talking about this. Organizing the world's information and making it universally accessible and
useful.

5 Google (@Google) | Twitter 
https://twitter.com/google
Google Wifi is now available at the @GoogleStore, @Amazon, @BestBuy and ... Fresh on #GoogleAllo: the Google Assistant in Brazilian Portuguese and
Hindi ...

6 גוגל (חברה) – ויקיפדיה
https://he.wikipedia.org/wiki/%D7%92%D7%95%D7%92%D7%9C_(%D7%97%D7%91%D7%A8%D7%94)
חברת גוגל (באנגלית: Google) היא תאגיד רב-לאומי אמריקאי בבעלותה של חברת האם אלפאבית. תאגיד גוגל, בין השאר, מספק שירותי חיפוש מידע ופרסום באינטרנט,
רשתות חברתיות ...

7 גוגל (מנוע חיפוש) – ויקיפדיה
https://he.wikipedia.org/wiki/%D7%92%D7%95%D7%92%D7%9C_(%D7%9E%D7%A0%D7%95%D7%A2_%D7%97%D7%99%D7%A4%D7%95%D7%A9)
גוגל (Google) הוא מנוע חיפוש הנמצא בבעלות חברת Google. זהו מנוע החיפוש ... בהתאם לכך, מאז שנת 2001 שולט מנוע החיפוש גוגל בשוק מנועי החיפוש. מנועי
החיפוש סורקים את ...
```

and `wget`:
```
googler (? for help) facebook
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=facebook&start=0
[DEBUG] Got exception: Remote end closed connection without response.
[DEBUG] Attempting to reconnect...
[DEBUG] Connecting to new host www.google.co.il
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 652, in fetch_page
    self._raw_get(url)
  File "/usr/local/bin/googler", line 736, in _raw_get
    self._resp = self._conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/googler", line 614, in new_connection
    self._conn.connect(self._notweak)
  File "/usr/local/bin/googler", line 166, in connect
    ssl_version=ssl.PROTOCOL_TLSv1_2)
  File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2166, in <module>
    main()
  File "/usr/local/bin/googler", line 2155, in main
    repl.cmdloop()
  File "/usr/local/bin/googler", line 1809, in cmdloop
    self.do_google(cmd)
  File "/usr/local/bin/googler", line 1734, in do_google
    self.fetch_and_display()
  File "/usr/local/bin/googler", line 1519, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1679, in fetch_and_display
    self.fetch()
  File "/usr/local/bin/googler", line 1519, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1610, in fetch
    page = self._conn.fetch_page(self._google_url.relative())
  File "/usr/local/bin/googler", line 656, in fetch_page
    self.renew_connection()
  File "/usr/local/bin/googler", line 625, in renew_connection
    self.new_connection(timeout=timeout)
  File "/usr/local/bin/googler", line 617, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.co.il: EOF occurred in violation of protocol (_ssl.c:645).


$ wget "www.google.com/search?ie=UTF-8&num=10&oe=UTF-8&q=facebook&start=0"
--2016-12-08 00:14:28--  http://www.google.com/search?ie=UTF-8&num=10&oe=UTF-8&q=facebook&start=0
Resolving www.google.com (www.google.com)... 194.90.196.31, 194.90.196.49, 194.90.196.24, ...
Connecting to www.google.com (www.google.com)|194.90.196.31|:80... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: http://www.google.com/search?ie=UTF-8&num=10&oe=UTF-8&q=facebook&start=0&safe=active [following]
--2016-12-08 00:14:30--  http://www.google.com/search?ie=UTF-8&num=10&oe=UTF-8&q=facebook&start=0&safe=active
Connecting to www.google.com (www.google.com)|194.90.196.31|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.google.co.il/search?ie=UTF-8&num=10&oe=UTF-8&q=facebook&start=0&safe=active&gws_rd=cr&ei=v4lIWI2lH8H2ULDBr9AO [following]
--2016-12-08 00:14:30--  http://www.google.co.il/search?ie=UTF-8&num=10&oe=UTF-8&q=facebook&start=0&safe=active&gws_rd=cr&ei=v4lIWI2lH8H2ULDBr9AO
Resolving www.google.co.il (www.google.co.il)... 194.90.196.20, 194.90.196.48, 194.90.196.59, ...
Reusing existing connection to www.google.com:80.
HTTP request sent, awaiting response... 403 Forbidden
2016-12-08 00:14:31 ERROR 403: Forbidden.
```

Some more output:
```
$ googler google
[ERROR] Failed to connect to www.google.com: EOF occurred in violation of protocol (_ssl.c:645).
```

**Comment by zmwangx** [comment]
## Symptoms summarized

- Sometimes it can't get past the SSL handshake with www.google.com;
- Sometimes it's able to connect to www.google.com, but fails at the handshake stage with www.google.co.il;
- Sometimes it manages to get through.

## Diagnosis

Not a bug. Your connection to Google is spotty.

Being able to ping google.com doesn't mean you can successfully make request and receive responses; there are probably packet drops too. If wget can't successfully retrieve content, we can't, either.

Also, your wget invocation isn't using TLS, and the 403 status code looks highly suspicious. I've never seen Google returning 403. I suspect your HTTP requests are censored.

## Solution

There's no solution, but at least you might be able to improve your rate of success by aliasing `googler` to `googler --tld il`. This way you save yourself one connection and redirect.

**Comment by jarun** [comment]
@123yagel just to add to the above comment, I have exactly the same setup as yours (Ubuntu 16.04.1 with latest updates) but I couldn't reproduce the issue with 100 oneshot queries. I used `--tld il`.

This doesn't seem to be an issue with SSL. However, can you also try the `--notweak` option? And please test with the *latest in mater*.
