### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:833)

### ISSUE THREAD

**Issue by kenorb** [jarun/googler#224]
#### Bug report

I've got the same issue as in GH-151.

```
$ googler -d
[DEBUG] googler version 3.5
[DEBUG] Python version 3.6.5
[DEBUG] Connecting to new host www.google.com
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 733, in new_connection
    self._conn.connect(self._notweak)
  File "/usr/local/bin/googler", line 268, in connect
    self.sock = ssl_context.wrap_socket(sock)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2572, in <module>
    main()
  File "/usr/local/bin/googler", line 2546, in main
    repl = GooglerCmd(opts)
  File "/usr/local/bin/googler", line 1777, in __init__
    notweak=opts.notweak)
  File "/usr/local/bin/googler", line 676, in __init__
    self.new_connection(host, port=port, timeout=timeout)
  File "/usr/local/bin/googler", line 736, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.com: EOF occurred in violation of protocol (_ssl.c:833).
```

### Details

```
$ googler --version
3.5
$ python --version
Python 2.7.10
$ openssl version
LibreSSL 2.2.7
$ macosver | paste -sd";"
ProductBuildVersion 17C2120;ProductCopyright 1983-2017 Apple Inc.;ProductName Mac OS X;ProductUserVisibleVersion 10.13.2;ProductVersion 10.13.2
$ curl -V
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
$ openssl s_client -showcerts -connect www.google.com:443 </dev/null
CONNECTED(00000005)
140735733224328:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/ssl/s23_lib.c:124:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 318 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```

It works for `curl`:

```
$ curl -vvv https://www.google.com/ > /dev/null
* TCP_NODELAY set
* Connected to www.google.com (172.217.16.68) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2940 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [149 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=www.google.com
*  start date: Mar 13 18:33:02 2018 GMT
*  expire date: Jun  5 18:16:00 2018 GMT
*  issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb12500e800)
> GET / HTTP/2
> Host: www.google.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Wed, 04 Apr 2018 10:55:29 GMT
< expires: -1
< cache-control: private, max-age=0
< content-type: text/html; charset=ISO-8859-1
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< server: gws
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< set-cookie: 1P_JAR=2018-04-04-10; expires=Fri, 04-May-2018 10:55:29 GMT; path=/; domain=.google.com
< set-cookie: NID=127=uvVh4zVxx5ILx65EHwFWMMvX7Wf5em363pkWWbuel172XeoKvcg3sFzMnhTSQkBoijc_BgIN9Zb8e-gHGlObEQctJ48-VHznfzDwyGcmWe2gKldkYT8aoOCGvU0KERYh; expires=Thu, 04-Oct-2018 10:55:29 GMT; path=/; domain=.google.com; HttpOnly
< alt-svc: hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35"
< accept-ranges: none
< vary: Accept-Encoding
< 
{ [1380 bytes data]
100 11736    0 11736    0     0  89571      0 --:--:-- --:--:-- --:--:-- 90276
* Connection #0 to host www.google.com left intact
```

When running with `--tld il`, it reads that the host is down, although it works as well with `curl`.

```
$ googler -d --tld il
[DEBUG] googler version 3.5
[DEBUG] Python version 3.6.5
[DEBUG] Connecting to new host www.google.co.il
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 733, in new_connection
    self._conn.connect(self._notweak)
  File "/usr/local/bin/googler", line 242, in connect
    self.timeout, self.source_address)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 64] Host is down

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2572, in <module>
    main()
  File "/usr/local/bin/googler", line 2546, in main
    repl = GooglerCmd(opts)
  File "/usr/local/bin/googler", line 1777, in __init__
    notweak=opts.notweak)
  File "/usr/local/bin/googler", line 676, in __init__
    self.new_connection(host, port=port, timeout=timeout)
  File "/usr/local/bin/googler", line 736, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.co.il: [Errno 64] Host is down.
```
Works with `curl`:

```
$ curl -svvv https://www.google.co.il/ > /dev/null
*   Trying 172.217.16.67...
* TCP_NODELAY set
* Connected to www.google.co.il (172.217.16.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2305 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=*.google.co.il
*  start date: Mar 13 19:44:22 2018 GMT
*  expire date: Jun  5 18:18:00 2018 GMT
*  issuer: C=US; O=Google Trust Services; CN=Google Internet Authority G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ff1d480dc00)
> GET / HTTP/2
> Host: www.google.co.il
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Wed, 04 Apr 2018 10:59:43 GMT
< expires: -1
< cache-control: private, max-age=0
< content-type: text/html; charset=windows-1255
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< server: gws
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< set-cookie: 1P_JAR=2018-04-04-10; expires=Fri, 04-May-2018 10:59:43 GMT; path=/; domain=.google.co.il
< set-cookie: NID=127=d1Sl9CvGabbCnbHUs4IJBQAq2SPTuK-yysqsJPxIaCG5LHWvjkZIe9poNsja7JIjrxw1HSANq7fOnRmNwipvbn7PF7M3zz1JTlMHiCErXZxmFzeefHZt5D0bGLNjZULP; expires=Thu, 04-Oct-2018 10:59:43 GMT; path=/; domain=.google.co.il; HttpOnly
< alt-svc: hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35"
< accept-ranges: none
< vary: Accept-Encoding
< 
{ [1380 bytes data]
* Connection #0 to host www.google.co.il left intact
```

**Comment by kenorb** [comment]
I think it could be related to _Little Snitch_ firewall upgrade, let me test it after the restart.

**Comment by kenorb** [comment]
Got it working, restart helped.
