### ISSUE TITLE
Using reader as the url handler?

### ISSUE THREAD

**Issue by for-coursera** [jarun/googler#225]
Further to the [instructions](https://github.com/jarun/googler/wiki/Terminal-Reading-Mode-or-Reader-View#using-reader) provided in the Wiki, I created a `reader` script to be used with `googler`. It has 755 permissions, and is in my `$PATH`:

    > which reader
    /Users/me/.local/bin/reader

Now, I can use it absolutely OK if running from the command line (like `reader http://fortune.com/2018/04/07/apple-curved-iphone-siri/`). However, if run with `googler` like this:

    googler -N --url-handler reader --debug apple

I receive the following error:

    [DEBUG] Opening http://fortune.com/2018/04/07/apple-curved-iphone-siri/
    Traceback (most recent call last):
      File "/usr/local/bin/googler", line 2572, in <module>
        main()
      File "/usr/local/bin/googler", line 2561, in main
        repl.cmdloop()
      File "/usr/local/bin/googler", line 2076, in cmdloop
        open_url(self._urltable[cmd])
      File "/usr/local/bin/googler", line 130, in open_url
        p = Popen([open_url.url_handler, url], stdin=PIPE)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    OSError: [Errno 8] Exec format error: '/Users/me/.local/bin/reader'

I run OS X 10.8.5, Python 3.6.3. Would be grateful for any advice, thanks!

**Comment by for-coursera** [comment]
Donno if related or not, but if I set the `$BROWSER` variable to either `/Users/me/.local/bin/reader` or just `reader` and then run `googler` without `--url-handler` key, like this: 

    googler -N --debug linux

then it reports it tries to open an url but just nothing happens:

    googler (? for help) 3
    [DEBUG] Opening https://www.makeuseof.com/tag/raspberry-pi-operating-systems-not-linux/
    googler (? for help)

**Comment by jarun** [comment]
I have:

1

```
~$ which reader
/usr/local/bin/reader
~$ cat /usr/local/bin/reader
#!/bin/sh

#elinks "http://justread.mpgarate.com/read?url=$1"

reader.py $1 -k _my_key_ -w 100 | jq -r '[
    (if .title then "# "+.title else empty end),
    (if .author then .author else empty end),
    .content.text
] | join("\n\n")' | $PAGER
~$
```

If I run:

    googler -n 7 -l en -N --url-handler reader apple
everything works fine for me.

**Comment by zmwangx** [comment]
Can't reproduce. Your python just can't launch your `reader`, so your observation about `BROWSER` is expected, as we suppress both stdout and stderr by default for browsers not on the whitelist.

Try these:

```
$ python3 -c 'import subprocess; p = subprocess.Popen(["reader", "https://example.com"]); p.communicate()'
$ python3 -c 'import subprocess; p = subprocess.Popen(["/Users/me/.local/bin/reader", "https://example.com"]); p.communicate()'
$ python3 -c 'import subprocess; subprocess.check_call(["reader", "https://example.com"])'
$ head /Users/me/.local/bin/reader
```

**Comment by jarun** [comment]
Probably move your script to a non-user-specific location, ensure you make it executable and try.

**Comment by zmwangx** [comment]
Shouldn't matter, s/he claimed it's in PATH and executable, unless the claim's false. Python doesn't actively modify your PATH in runtime, we don't either, and there's no shell rc in the way since we don't do `shell=True`.

**Comment by jarun** [comment]
Yes, you are right. I think your commands would shed some light.

**Comment by jarun** [comment]
Also @for-coursera can you please share the complete content of your script?
