### ISSUE TITLE
Googler dis-functional on WSL (Windows 10 Subsystem for Linux)

### ISSUE THREAD

**Issue by sginsbourg** [jarun/googler#248]
googler --count 20 --exact --nocolor --noua --noprompt --debug "something" filetype:pdf
[DEBUG] googler version 3.5
[DEBUG] Python version 3.6.6
[DEBUG] User Agent is disabled
[DEBUG] Connecting to new host www.google.com
[DEBUG] setsockopt failed
Traceback (most recent call last):
  File "/usr/bin/googler", line 733, in new_connection
    self._conn.connect(self._notweak)
  File "/usr/bin/googler", line 268, in connect
    self.sock = ssl_context.wrap_socket(sock)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/googler", line 2572, in <module>
    main()
  File "/usr/bin/googler", line 2546, in main
    repl = GooglerCmd(opts)
  File "/usr/bin/googler", line 1777, in __init__
    notweak=opts.notweak)
  File "/usr/bin/googler", line 676, in __init__
    self.new_connection(host, port=port, timeout=timeout)
  File "/usr/bin/googler", line 736, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.com: [Errno 0] Error.

**Comment by zmwangx** [comment]
I can't reproduce on Windows 10 Pro 1809, Ubuntu Bionic (18.04.1)-based WSL, Python 3.6.6 from default repository (though the stupid package says `3.6.5-3ubuntu1`, not sure which one to trust), and googler 3.5 from default repository.

More information required. From my limited understanding of TLS, a handshake failure means either this is a network issue, which we can do nothing about, or client and server can't agree on a protocol, which is unlikely, seeing that you have rather recent kernel, OpenSSL, and Python.

(Aside: WTF is errno 0? They didn't bother to implement errno, the backbone of syscall error handling? That's weird.)

**Comment by zmwangx** [comment]
(Also, bug reports should be directed at git master. It should go to the packager if the bug is not reproducible on master.)

**Comment by zmwangx** [comment]
A bit of follow-up: did some digging, and I spoke too soon. The puzzling errno 0 isn't a problem of WSL's syscall architecture; rather, it seems to be an unfortunate corner of Python due to insufficient info from OpenSSL (see [bpo-10808](https://bugs.python.org/issue10808) and [bpo-31122](https://bugs.python.org/issue31122)). Basically, it appears that in currently known cases, errno 0 means the connection is unexpectedly closed — typically known as `ssl.SSLEOFError`.

Without strong indication otherwise, I file this under network problems beyond our control.

**Comment by jarun** [comment]
> Without strong indication otherwise, I file this under network problems beyond our control.

I concur, I use `googler` on WSL from time to time. Ubuntu 16.04. No issues.

**Comment by kriegaex** [comment]
I hope it is okay to comment here instead of opening a similar issue, but I can do so if you like. I also cannot use googler on the Win10 Linux subsystem with Debian/GNU Linux installed and the distro apt-upgraded.

```
$ uname -a
Linux HGDECLFR002710 4.4.0-17134-Microsoft #285-Microsoft Thu Aug 30 17:31:00 PST 2018 x86_64 GNU/Linux

$ PYTHONIOENCODING=utf-8 googler scrum
[ERROR] Failed to connect to www.google.com: [Errno 92] Protocol not available.
```

**Comment by jarun** [comment]
Thanks for the note!

**Comment by zmwangx** [comment]
The current version (9.5) of Debian Stretch is still stuck on googler v2.9, almost two-year old. I can confirm it doesn't work on WSL.

On the other hand, `--upgrade` is supposed to be disabled by packagers... We have the `disable-self-upgrade` target https://github.com/jarun/googler/blob/ea5ca238cc2a3aad9ae2a6a3e541424c5f130332/Makefile#L25-L30 for that exact purpose... But the Debian package installs the `googler` script as is (other than replacing the shebang, which is done by `dh-python` automatically as I believe). Not sure that's a great idea.

**Comment by jarun** [comment]
I believe when users raise issues the ask was to check with master first. So my understanding was the report is on master.

@szlin can you please take care of this?

**Comment by zmwangx** [comment]
The OP was reporting on the Ubuntu Bionic package (googler v3.5) [1] on Ubuntu-based WSL.

The follow-up question (not actually related) was about on the Debian Stretch package (googler v2.9) [2] on Debian-based WSL. Of course, kriegaex then ran `googler --upgrade` (I was saying this should be disabled by packagers, since it causes version mismatch between package registry — `dkpg` in this case — and actual binary) which brought `/usr/bin/googler` to v3.7.1, which is just master at this point.

I am of the opinion that if you want to stay on the latest release, you either ask your distro/repo to upgrade to the latest (apparently not gonna happen with Debian/Ubuntu, but it is very much possible with Arch/Homebrew/etc.), or make the conscious decision to install the standalone binary and use the self-upgrade mechanism. Mix and matching outdated repo and self-upgrade, resulting in

```console
$ dpkg-query -f '${Version}\n' -W googler
2.9.0-1
$ googler -v
3.7.1
```

makes me deeply uncomfortable...

But maybe it's just me being a purist. I can see how

```console
$ apt update
$ apt install -y googler
$ googler -u
```

is easier than

```console
$ curl -o /usr/local/bin/googler https://raw.githubusercontent.com/jarun/googler/master/googler
$ chmod +x /usr/local/bin/googler
```

But of course, at some point you run `apt dist-upgrade -y` and googler is accidentally "downgraded".

[1] https://packages.ubuntu.com/bionic/googler
[2] https://packages.debian.org/stretch/googler

**Comment by jarun** [comment]
I would like to get inputs from @szlin on this as well. Probably the best option for us going forward is to redirect these distro-specific issues to the corresponding maintainer. My understanding on the mechanisms to upgrade/update on the distros is admittedly limited. There are so many of them out there!

And yes, for packages which I use regularly (like rg, bat) I like to get the _latest from the repo_ without any fuss. Because 1000s of other packages work that way.

**Comment by zmwangx** [comment]
> I like to get the latest from the repo

Debian is an ancient African word meaning outdated — sorry, I meant stable — software.

**Comment by zmwangx** [comment]
To be fair, if you use an outdated rg (bad example apparently, rg simply doesn't exist in current Debian/Ubuntu stable), you only miss out on new features (and maybe minor bug fixes). But if you use an outdated package that talks to third-party web services that change over time, e.g. googler or youtube-dl, chances are it will fail, at least eventually.

**Comment by sginsbourg** [comment]
Update: Uninstalling Kaspersky AV solved all setsockopt problems.
I can now work with Googler on WSL just like on any other Linux.

**Comment by zmwangx** [comment]
Ah, AV products, gotta love those.

**Comment by sginsbourg** [comment]
BTW - smooth upgrade to [jarun/googler] v3.7.1

Well done ! Thank you guys for your efforts !

**Comment by szlin** [comment]
> The OP was reporting on the Ubuntu Bionic package (googler v3.5) [1] on Ubuntu-based WSL.
> 
> The follow-up question (not actually related) was about on the Debian Stretch package (googler v2.9) [2] on Debian-based WSL. Of course, kriegaex then ran `googler --upgrade` (I was saying this should be disabled by packagers, since it causes version mismatch between package registry — `dkpg` in this case — and actual binary) which brought `/usr/bin/googler` to v3.7.1, which is just master at this point.
> 
> I am of the opinion that if you want to stay on the latest release, you either ask your distro/repo to upgrade to the latest (apparently not gonna happen with Debian/Ubuntu, but it is very much possible with Arch/Homebrew/etc.), or make the conscious decision to install the standalone binary and use the self-upgrade mechanism. Mixing and matching outdated repo and self-upgrade, resulting in
> 
> ```
> $ dpkg-query -f '${Version}\n' -W googler
> 2.9.0-1
> $ googler -v
> 3.7.1
> ```
> 
> makes me deeply uncomfortable...
> 
> But maybe it's just me being a purist. I can see how
> 
> ```
> $ apt update
> $ apt install -y googler
> $ googler -u
> ```
> 
> is easier than
> 
> ```
> $ curl -o /usr/local/bin/googler https://raw.githubusercontent.com/jarun/googler/master/googler
> $ chmod +x /usr/local/bin/googler
> ```
> 
> But of course, at some point you run `apt dist-upgrade -y` and googler is accidentally "downgraded".
> 
> [1] https://packages.ubuntu.com/bionic/googler
> [2] https://packages.debian.org/stretch/googler

Indeed, the "package version is outdated" is a common feedback for Debian stable. 

In Debian policy, the major version of package won't be bumped in stable version. But there is another way to use latest version of googler in Debian 9 [1], that is to repack googler and upload it into "stretch-backports" [2]. user can use it after adding proper URL [3].

I can find my spare time to do it if you think it is necessary.

[1] https://backports.debian.org/
[2] https://backports.debian.org/news/stretch-backports/
[3] https://backports.debian.org/Instructions/

**Comment by jarun** [comment]
> I can find my spare time to do it if you think it is necessary.

It would be great if you can do that.

**Comment by szlin** [comment]
The backport package was merged [1].

Please add this line to

`deb http://ftp.debian.org/debian stretch-backports main`

 your sources.list and thus you can install newest version of googler in Debian 9.

[1] https://packages.debian.org/source/stretch-backports/googler
